// Central mock data source for the DPR-AI dashboard
export const kpiStats = [
  {
    id: 'total',
    label: 'Total DPRs',
    value: '524',
    icon: 'FileText',
    color: 'blue',
    change: '+12 this month',
    changeType: 'up',
  },
  {
    id: 'pending',
    label: 'Pending Review',
    value: '42',
    icon: 'Clock',
    color: 'amber',
    change: '8 urgent',
    changeType: 'down',
  },
  {
    id: 'high-risk',
    label: 'High Risk Projects',
    value: '18',
    icon: 'ShieldAlert',
    color: 'red',
    change: '+3 since last week',
    changeType: 'down',
  },
  {
    id: 'approved',
    label: 'Approved This Month',
    value: '67',
    icon: 'CheckCircle',
    color: 'green',
    change: '89% approval rate',
    changeType: 'up',
  },
  {
    id: 'funds',
    label: 'Unutilised Funds (₹Cr)',
    value: '9,384',
    icon: 'IndianRupee',
    color: 'purple',
    change: 'Down from ₹11,200 Cr',
    changeType: 'up',
  },
  {
    id: 'states',
    label: 'Active States',
    value: '8',
    icon: 'Map',
    color: 'cyan',
    change: 'All NE states active',
    changeType: 'up',
  },
];

export const recentDprs = [
  {
    id: 'DPR-2025-0842',
    title: 'NH-217 Four-Lane Highway Extension',
    state: 'Arunachal Pradesh',
    sector: 'Roads',
    cost: '₹ 842 Cr',
    status: 'Pending',
    riskLevel: 'High',
    qualityScore: 58,
    submittedDate: '21 Apr 2026',
    submittedBy: 'ARPWD Office',
  },
  {
    id: 'DPR-2025-0841',
    title: 'Guwahati Multi-Modal Logistics Park',
    state: 'Assam',
    sector: 'Infrastructure',
    cost: '₹ 320 Cr',
    status: 'Review',
    riskLevel: 'Medium',
    qualityScore: 74,
    submittedDate: '20 Apr 2026',
    submittedBy: 'ADoT, Assam',
  },
  {
    id: 'DPR-2025-0840',
    title: 'Manipur Hydro Power Plant (60MW)',
    state: 'Manipur',
    sector: 'Power',
    cost: '₹ 560 Cr',
    status: 'Approved',
    riskLevel: 'Low',
    qualityScore: 88,
    submittedDate: '19 Apr 2026',
    submittedBy: 'MSPDCL',
  },
  {
    id: 'DPR-2025-0839',
    title: 'Shillong Smart City Phase 2',
    state: 'Meghalaya',
    sector: 'Urban',
    cost: '₹ 218 Cr',
    status: 'Approved',
    riskLevel: 'Low',
    qualityScore: 91,
    submittedDate: '18 Apr 2026',
    submittedBy: 'UDA Meghalaya',
  },
  {
    id: 'DPR-2025-0838',
    title: 'Mizoram Rural Broadband Connectivity',
    state: 'Mizoram',
    sector: 'Telecom',
    cost: '₹ 95 Cr',
    status: 'Pending',
    riskLevel: 'Medium',
    qualityScore: 67,
    submittedDate: '17 Apr 2026',
    submittedBy: 'DoT Mizoram',
  },
  {
    id: 'DPR-2025-0837',
    title: 'Nagaland Primary Health Center Upgrade',
    state: 'Nagaland',
    sector: 'Healthcare',
    cost: '₹ 48 Cr',
    status: 'Review',
    riskLevel: 'Low',
    qualityScore: 82,
    submittedDate: '16 Apr 2026',
    submittedBy: 'NHM Nagaland',
  },
  {
    id: 'DPR-2025-0836',
    title: 'Sikkim Eco-Tourism Circuit Development',
    state: 'Sikkim',
    sector: 'Tourism',
    cost: '₹ 72 Cr',
    status: 'Rejected',
    riskLevel: 'High',
    qualityScore: 41,
    submittedDate: '15 Apr 2026',
    submittedBy: 'Tourism Dept Sikkim',
  },
  {
    id: 'DPR-2025-0835',
    title: 'Tripura Rubber Plantation Expansion',
    state: 'Tripura',
    sector: 'Agriculture',
    cost: '₹ 124 Cr',
    status: 'Processing',
    riskLevel: 'Medium',
    qualityScore: 71,
    submittedDate: '14 Apr 2026',
    submittedBy: 'Agri Dept Tripura',
  },
];

export const qualityDimensions = [
  { dimension: 'Technical Soundness', score: 72, color: '#2196f3' },
  { dimension: 'Financial Realism', score: 65, color: '#f59e0b' },
  { dimension: 'Risk Identification', score: 58, color: '#ef4444' },
  { dimension: 'Timeline Feasibility', score: 70, color: '#8b5cf6' },
  { dimension: 'Environmental Compliance', score: 84, color: '#10b981' },
  { dimension: 'Stakeholder Engagement', score: 78, color: '#06b6d4' },
  { dimension: 'Procurement Clarity', score: 69, color: '#f97316' },
  { dimension: 'Sustainability', score: 62, color: '#ec4899' },
];

export const trendData = [
  { month: 'Oct', submitted: 38, approved: 28, rejected: 5, avgScore: 68 },
  { month: 'Nov', submitted: 45, approved: 31, rejected: 7, avgScore: 70 },
  { month: 'Dec', submitted: 52, approved: 38, rejected: 8, avgScore: 71 },
  { month: 'Jan', submitted: 48, approved: 35, rejected: 6, avgScore: 73 },
  { month: 'Feb', submitted: 61, approved: 47, rejected: 9, avgScore: 74 },
  { month: 'Mar', submitted: 55, approved: 42, rejected: 7, avgScore: 76 },
  { month: 'Apr', submitted: 42, approved: 34, rejected: 4, avgScore: 78 },
];

export const sectorBreakdown = [
  { name: 'Roads', value: 142, color: '#2196f3' },
  { name: 'Power', value: 89, color: '#f59e0b' },
  { name: 'Healthcare', value: 76, color: '#10b981' },
  { name: 'Education', value: 68, color: '#8b5cf6' },
  { name: 'Tourism', value: 54, color: '#06b6d4' },
  { name: 'Agriculture', value: 47, color: '#f97316' },
  { name: 'Urban', value: 48, color: '#ec4899' },
];

export const statePerformance = [
  { state: 'Arunachal Pradesh', dprs: 98, avgScore: 64, utilisation: 72 },
  { state: 'Assam', dprs: 142, avgScore: 78, utilisation: 85 },
  { state: 'Manipur', dprs: 67, avgScore: 71, utilisation: 68 },
  { state: 'Meghalaya', dprs: 54, avgScore: 82, utilisation: 91 },
  { state: 'Mizoram', dprs: 38, avgScore: 69, utilisation: 62 },
  { state: 'Nagaland', dprs: 45, avgScore: 74, utilisation: 77 },
  { state: 'Sikkim', dprs: 29, avgScore: 80, utilisation: 88 },
  { state: 'Tripura', dprs: 51, avgScore: 73, utilisation: 79 },
];

export const riskAlerts = [
  {
    id: '1',
    dprId: 'DPR-2025-0842',
    title: 'NH-217 Highway Extension',
    state: 'Arunachal Pradesh',
    riskScore: 82,
    riskFactors: ['Himalayan terrain complexity', 'Monsoon constraints', 'Missing geological survey'],
    flaggedAt: '2 hours ago',
  },
  {
    id: '2',
    dprId: 'DPR-2025-0836',
    title: 'Sikkim Eco-Tourism Circuit',
    state: 'Sikkim',
    riskScore: 76,
    riskFactors: ['Incomplete environmental clearance', 'Budget underestimation (est. 23%)'],
    flaggedAt: '1 day ago',
  },
  {
    id: '3',
    dprId: 'DPR-2025-0829',
    title: 'Manipur Border Road Phase 3',
    state: 'Manipur',
    riskScore: 73,
    riskFactors: ['Security zone constraints', 'Contractor qualification gaps'],
    flaggedAt: '2 days ago',
  },
];

export const radarData = [
  { subject: 'Technical', A: 72, fullMark: 100 },
  { subject: 'Financial', A: 65, fullMark: 100 },
  { subject: 'Risk ID', A: 58, fullMark: 100 },
  { subject: 'Timeline', A: 70, fullMark: 100 },
  { subject: 'Environment', A: 84, fullMark: 100 },
  { subject: 'Stakeholder', A: 78, fullMark: 100 },
  { subject: 'Procurement', A: 69, fullMark: 100 },
  { subject: 'Sustainability', A: 62, fullMark: 100 },
];
