// TOPLINE

'use client';
import { Topbar } from '@/components/layout/Topbar';
import { Lightbulb, TrendingUp, AlertTriangle, ChevronRight, Zap } from 'lucide-react';
import Link from 'next/link';
import { useState, useEffect, useCallback } from 'react';

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';

const PRIORITIES = ['All', 'Critical', 'High', 'Medium', 'Low'];
const CATEGORIES = ['All', 'Technical', 'Financial', 'Environmental', 'Timeline', 'Procurement', 'Compliance', 'Risk', 'Sustainability', 'Stakeholder'];

const priorityBadgeClass: Record<string, string> = {
  critical: 'badge-critical',
  high: 'badge-high',
  medium: 'badge-medium',
  low: 'badge-low',
};

interface Recommendation {
  id: string;
  dprId: string;
  dprTitle: string;
  state: string;
  category: string;
  priority: string;
  title: string;
  description: string;
  impact: string;
  actionableSteps: string[];
  generatedAt: string;
}

function formatDate(iso: string): string {
  try {
    const d = new Date(iso);
    const now = new Date();
    const diffMs = now.getTime() - d.getTime();
    const diffDays = Math.floor(diffMs / 86400000);
    if (diffDays === 0) return 'today';
    if (diffDays === 1) return '1 day ago';
    if (diffDays < 30) return `${diffDays} days ago`;
    return d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
  } catch { return iso; }
}

export default function RecommendationsPage() {
  const [filterPriority, setFilterPriority] = useState('All');
  const [filterCategory, setFilterCategory] = useState('All');
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [recommendations, setRecommendations] = useState<Recommendation[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const fetchRecommendations = useCallback(async () => {
    setError('');
    try {
      const res = await fetch(`${API_URL}/api/recommendations`);
      if (!res.ok) throw new Error(`Server error ${res.status}`);
      const data = await res.json();
      setRecommendations(data);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Failed to load recommendations');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { fetchRecommendations(); }, [fetchRecommendations]);

  const filtered = recommendations.filter((r) => {
    const matchPriority = filterPriority === 'All' || r.priority === filterPriority.toLowerCase();
    const matchCategory = filterCategory === 'All' || r.category === filterCategory;
    return matchPriority && matchCategory;
  });

  const criticalCount = recommendations.filter(r => r.priority === 'critical').length;
  const highCount = recommendations.filter(r => r.priority === 'high').length;
  const mediumCount = recommendations.filter(r => r.priority === 'medium').length;
  const uniqueDprs = new Set(recommendations.map(r => r.dprId)).size;

  return (
    <>
      <Topbar
        title="AI Recommendations"
        subtitle="Actionable improvement suggestions generated by the AI engine"
      />
      <div className="page-content fade-in">

        {/* Header banner */}
        <div style={{
          display: 'flex', gap: 12, padding: '14px 16px',
          background: 'linear-gradient(135deg, rgba(139,92,246,0.08), rgba(33,150,243,0.08))',
          border: '1px solid rgba(139,92,246,0.2)',
          borderRadius: 10, marginBottom: 20, alignItems: 'center',
        }}>
          <Lightbulb size={18} color="var(--accent-purple)" style={{ flexShrink: 0 }} />
          <div style={{ fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.6 }}>
            {loading ? (
              <span style={{ color: 'var(--text-muted)' }}>Loading recommendations…</span>
            ) : (
              <>
                <strong style={{ color: 'var(--text-primary)' }}>{recommendations.length} recommendations</strong> generated
                across <strong style={{ color: 'var(--text-primary)' }}>{uniqueDprs} DPRs</strong>.
                Recommendations are AI-generated based on quality assessment scores, risk analysis, sector benchmarks, and NE regional compliance requirements.
              </>
            )}
          </div>
        </div>

        {/* Error */}
        {error && (
          <div style={{ padding: '12px 16px', background: 'rgba(239,68,68,0.08)', border: '1px solid rgba(239,68,68,0.2)', borderRadius: 10, marginBottom: 16, fontSize: 13, color: '#ef4444' }}>
            ⚠ {error} —{' '}
            <button style={{ background: 'none', border: 'none', color: '#ef4444', cursor: 'pointer', fontWeight: 600 }} onClick={fetchRecommendations}>
              Retry
            </button>
          </div>
        )}

        {/* Stats */}
        <div className="rec-stat-grid">
          <div className="rec-stat-card">
            <div className="rec-stat-value" style={{ color: 'var(--text-primary)' }}>{loading ? '…' : recommendations.length}</div>
            <div className="rec-stat-label">Total Recommendations</div>
          </div>
          <div className="rec-stat-card">
            <div className="rec-stat-value" style={{ color: 'var(--accent-red)' }}>{loading ? '…' : criticalCount}</div>
            <div className="rec-stat-label">Critical Priority</div>
          </div>
          <div className="rec-stat-card">
            <div className="rec-stat-value" style={{ color: 'var(--accent-amber)' }}>{loading ? '…' : highCount}</div>
            <div className="rec-stat-label">High Priority</div>
          </div>
          <div className="rec-stat-card">
            <div className="rec-stat-value" style={{ color: 'var(--accent-blue)' }}>{loading ? '…' : mediumCount}</div>
            <div className="rec-stat-label">Medium Priority</div>
          </div>
        </div>

        {/* Filters */}
        <div className="card" style={{ marginBottom: 20 }}>
          <div className="card-body" style={{ padding: '14px 20px' }}>
            <div style={{ display: 'flex', gap: 20, alignItems: 'center', flexWrap: 'wrap' }}>
              <div>
                <div style={{ fontSize: 10, fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: 8 }}>
                  Priority
                </div>
                <div className="filter-chips">
                  {PRIORITIES.map(p => (
                    <button
                      key={p}
                      className={`filter-chip ${filterPriority === p ? 'active' : ''}`}
                      onClick={() => setFilterPriority(p)}
                    >
                      {p}
                      {p !== 'All' && (
                        <span style={{ marginLeft: 4, opacity: 0.7 }}>
                          ({recommendations.filter(r => r.priority === p.toLowerCase()).length})
                        </span>
                      )}
                    </button>
                  ))}
                </div>
              </div>
              <div style={{ width: 1, height: 40, background: 'var(--border)' }} />
              <div>
                <div style={{ fontSize: 10, fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: 8 }}>
                  Category
                </div>
                <div className="filter-chips">
                  {CATEGORIES.filter(c => c === 'All' || recommendations.some(r => r.category === c)).map(c => (
                    <button
                      key={c}
                      className={`filter-chip ${filterCategory === c ? 'active' : ''}`}
                      onClick={() => setFilterCategory(c)}
                    >
                      {c}
                    </button>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Results count */}
        <div style={{ fontSize: 13, color: 'var(--text-muted)', marginBottom: 14 }}>
          Showing <strong style={{ color: 'var(--text-primary)' }}>{filtered.length}</strong> recommendation{filtered.length !== 1 ? 's' : ''}
        </div>

        {/* Loading spinner */}
        {loading && (
          <div className="empty-state">
            <div className="empty-state-icon" style={{ fontSize: 28 }}>⟳</div>
            <div style={{ fontSize: 14, color: 'var(--text-muted)' }}>Loading AI recommendations…</div>
          </div>
        )}

        {/* Recommendation Cards */}
        {!loading && (
          <div className="rec-grid">
            {filtered.map((rec) => (
              <div key={rec.id} className={`rec-card priority-${rec.priority}`}>
                <div
                  className="rec-card-header"
                  style={{ cursor: 'pointer' }}
                  onClick={() => setExpandedId(expandedId === rec.id ? null : rec.id)}
                >
                  <div style={{ flex: 1 }}>
                    <div className="rec-card-title">
                      {rec.priority === 'critical' && <AlertTriangle size={14} color="#ef4444" style={{ marginRight: 6, verticalAlign: 'text-bottom' }} />}
                      {rec.title}
                    </div>
                    <div className="rec-card-meta">
                      <Link href={`/dpr/${rec.dprId}`} className="rec-dpr-link" onClick={(e) => e.stopPropagation()}>
                        {rec.dprId}
                      </Link>
                      <span>·</span>
                      <span>{rec.dprTitle}</span>
                      <span>·</span>
                      <span>{rec.state}</span>
                      <span>·</span>
                      <span>{formatDate(rec.generatedAt)}</span>
                    </div>
                  </div>
                  <div style={{ display: 'flex', gap: 6, alignItems: 'flex-start', flexShrink: 0 }}>
                    <span className={`cat-tag ${rec.category.toLowerCase()}`}>{rec.category}</span>
                    <span className={`badge ${priorityBadgeClass[rec.priority] || 'badge-medium'}`}>{rec.priority}</span>
                    <ChevronRight
                      size={16}
                      color="var(--text-muted)"
                      style={{
                        transition: 'transform 0.2s',
                        transform: expandedId === rec.id ? 'rotate(90deg)' : 'rotate(0deg)',
                        marginTop: 2,
                      }}
                    />
                  </div>
                </div>

                {expandedId === rec.id && (
                  <div className="rec-card-body fade-in">
                    <div className="rec-card-desc">{rec.description}</div>

                    <div className="rec-impact">
                      <TrendingUp size={14} style={{ flexShrink: 0 }} />
                      <span><strong>Impact:</strong> {rec.impact}</span>
                    </div>

                    <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.8px', marginBottom: 8 }}>
                      Actionable Steps
                    </div>
                    <div className="rec-steps">
                      {rec.actionableSteps.map((step, i) => (
                        <div key={i} className="rec-step">
                          <div className="rec-step-num">{i + 1}</div>
                          <span>{step}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>
        )}

        {/* Empty state */}
        {!loading && filtered.length === 0 && !error && (
          <div className="empty-state">
            <div className="empty-state-icon">💡</div>
            <div style={{ fontSize: 14, fontWeight: 600, color: 'var(--text-secondary)', marginBottom: 6 }}>
              {recommendations.length === 0
                ? 'No recommendations yet — upload and analyse a DPR first'
                : 'No recommendations match your filters'}
            </div>
            <div style={{ fontSize: 12, color: 'var(--text-muted)' }}>
              {recommendations.length === 0
                ? 'Recommendations are generated automatically after DPR analysis.'
                : 'Try adjusting the priority or category filters'}
            </div>
          </div>
        )}

        {/* Bottom info */}
        <div style={{
          marginTop: 24,
          padding: '14px 20px',
          background: 'rgba(33,150,243,0.06)',
          border: '1px solid rgba(33,150,243,0.15)',
          borderRadius: 10,
          display: 'flex', alignItems: 'center', gap: 10,
        }}>
          <Zap size={14} color="var(--accent-blue)" style={{ flexShrink: 0 }} />
          <div style={{ fontSize: 11, color: 'var(--text-muted)', lineHeight: 1.5 }}>
            Recommendations are generated using AI analysis of DPR quality dimensions, risk profiles, MoRTH/CPWD benchmarks,
            and historical project data from 200+ NE region projects. Last model update: April 2026.
          </div>
        </div>
      </div>
    </>
  );
}
